services:
  app:
    build:
      context: ./
      dockerfile: ./MailGatekeeper.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=local
      - mg_key=${mg_key}
    volumes:
      - ./MailGatekeeper.Api/appsettings.local.json:/app/appsettings.local.json:ro
    ports:
      - 5012:8080
